name: Deploy static HTML to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare static content
        run: echo "Static site — no build needed."

      - name: Deploy static HTML via ZipDeploy
        run: |
          zip -r static-html.zip .
          curl -X POST \
            -u "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9A0C7000D53E4BAABD328529567B638A }}" \
            -T static-html.zip \
            "https://static-html-gwhgfjezcpawcah9.scm.azurewebsites.net/api/zipdeploy"
